plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

ext {
	springCloudVersion = "2024.0.1"
}

group = 'com.framework'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	//Jpa
	//implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	//implementation 'org.springframework.boot:spring-boot-starter-jdbc'

	//R2DBC 사용을 위한 기본 설정 및 인프라 제공
	implementation("org.springframework.boot:spring-boot-starter-data-r2dbc")
	//mariaDB
	implementation 'org.mariadb:r2dbc-mariadb'

	//Gateway
	implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
	//redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	//모니터링이나 매트릭(metric)과 같은 기능을 HTTP와 JMX 엔드포인트를 통해 제공
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	//prometheus(metrics정보 제공)
	implementation 'io.micrometer:micrometer-registry-prometheus'

	//JWT
	implementation 'io.jsonwebtoken:jjwt:0.9.1'

	//Loki Logging logback
	//implementation 'com.github.loki4j:loki-logback-appender:1.5.1'

	//traceId, spanId 정보제공
	implementation 'io.micrometer:micrometer-tracing-bridge-brave'
	implementation 'io.zipkin.reporter2:zipkin-reporter-brave'

	//spring boot 3.X에서는 사용 못합
	//implementation 'org.springframework.cloud:spring-cloud-starter-sleuth'

	//lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}