server:
  port: 8080

spring:
  application:
    name: gw

  #R2DBC-mariadb 설정
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/gateway
    username: namanok
    password: namanok

# 운영 yml파일에는 아래 설정부분 제거(외부에서 refresh 방지)
# http://localhost:9000/actuator/gateway/routes 로 route 조회
management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info, prometheus
  endpoint:
    gateway:
      enabled: true # default: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"