server:
  port: 9000

spring:
  application:
    name: gw

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/gateway
    username: namanok
    password: namanok

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
#logging:
#  level:
#    org.hibernate:
#      type.descriptor.sql: trace
#      SQL: DEBUG

# 운영 yml파일에는 아래 설정부분 제거(외부에서 refresh 방지)
# http://localhost:9000/actuator/gateway/routes 로 route 조회
management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info, prometheus
  endpoint:
    gateway:
      enabled: true # default: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"